sudo: required
language: generic
dist: trusty
install:
    - sudo add-apt-repository "deb http://ftp.debian.org/debian jessie-backports main"
    - sudo apt-get -qq update
    - sudo apt-get install -t jessie-backports -y --force-yes gcc-arm-none-eabi libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib
script:
    - cd mchf-eclipse
    - make bootloader
    - make clean
    - make all
before_deploy:
    - sudo apt-get install -y doxygen graphviz
    - make docs > /dev/null && tar -czf docs.tar.gz -C .. docs
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: "SECURE TOKEN MISSING"
  on:
    repo: df8oe/mchf-github
    tags: true
